---
- name: Setup the secrets for deploy keys
  hosts: secrets
  tasks:
    - include_vars: "{{ playbook_dir }}/deploy-keys/keys.yml"
    - name: replace secret params with variables
      template:
        src: "{{ playbook_dir }}/params/secrets/secret.j2"
        dest: "{{ playbook_dir }}/params/secrets/{{ item.secret_name }}"
      with_items:
        - "{{ ci_cd_app }}"
        - "{{ spring }}"
        - "{{ vue }}"
    - include_role:
        name: openshift-applier/roles/openshift-applier