---
#### old way
#- import_playbook: bootstrap.yml
#- import_playbook: secrets.yml
#- import_playbook: tools.yml

### bootstrap.yml
- name: Create Projects and Policies
  hosts: bootstrap
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier

### secrets.yml
- name: Create secrets
  hosts: secrets
  tasks:
    - include_vars: "{{ playbook_dir }}/secrets/keys.yml"
    - include_vars: "{{ playbook_dir }}/secrets/user-pass.yml"
    - include_role:
        name: openshift-applier/roles/openshift-applier

### tools.yml
- name: Create CI/CD tools
  hosts: tools
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier
      tags:
        - openshift-applier

- name: configure nexus #TODO there was something with SSH tunneling there i think it can just be moved up above
  hosts: localhost
  tasks:
    - name: set namespace
      set_fact:
        nexus_namespace: "{{ ci_cd_namespace }}"
    - include_role:
        name: infra-ansible/roles/config-nexus
      tags:
        - configure-nexus
