---
ansible_connection: local

build:
  SOURCE_REPOSITORY_URL: "{{ ci_cd.repository }}" #todo need a different repo since this is removed
  SOURCE_REPOSITORY_SECRET: "{{ ci_cd.SECRET_NAME }}"
  SOURCE_REPOSITORY_REF: "master"
  IMAGE_STREAM_NAMESPACE: "{{ ci_cd.NAMESPACE }}"
jenkins:
  NAMESPACE: "{{ ci_cd.NAMESPACE }}"
  SLACK_BASE_URL: https://fake-at-fake-dot-com.slack.com/services/hooks/jenkins-ci/ #TODO: put real test slack in here
  SLACK_ROOM: builds
  SLACK_TOKEN: notrealtokenMAKEMEASECRET #TODO: make this a real secret
  JENKINS_URL: https://jenkins-{{ ci_cd.NAMESPACE }}.apps.{{ base_openshift_url }}/ #TODO: variablize jenkins name?
  SHARED_LIB_REPO: "git@github.com:redhat-cop/pipeline-library.git"
  SHARED_LIB_NAME: "pipeline-library"
  SHARED_LIB_REF: "master" #todo need a tag here in that repo ^
  SHARED_LIB_SECRET: "{{ ci_cd.SECRET_NAME }}"

openshift_cluster_content:
- object: ci-cd-builds
  content:
  - name: jenkins-s2i
    template: "https://raw.githubusercontent.com/rht-labs/openshift-templates/v1.0/jenkins-s2i-build/template.yml"
    params: "{{ playbook_dir }}/params/jenkins/build"
    namespace: "{{ ci_cd.NAMESPACE }}"
    tags:
    - jenkins
    - jenkins-build
  - name: tool-box
    template: "https://raw.githubusercontent.com/rht-labs/openshift-templates/v1.0/docker-build/template.yml"
    params: "{{ playbook_dir }}/params/tool-box/build"
    namespace: "{{ ci_cd_namespace }}"
    tags:
      - tool-box
  - name: hoverfly
    template: "https://raw.githubusercontent.com/rht-labs/openshift-templates/v1.0/docker-build/template.yml"
    params: "{{ playbook_dir }}/params/hoverfly/build"
    namespace: "{{ ci_cd_namespace }}"
    tags:
      - hoverfly
  - name: sonarqube
    template: "https://raw.githubusercontent.com/rht-labs/openshift-templates/v1.0/docker-build/template.yml"
    params: "{{ playbook_dir }}/params/sonarqube/build"
    namespace: "{{ ci_cd.NAMESPACE }}"
    tags:
      - sonarqube
      - sonarqube-build
- object: jenkins-slave-nodes
  content:
  - name: jenkins-slave-mvn
    template: "https://raw.githubusercontent.com/redhat-cop/containers-quickstarts/v1.3/jenkins-slaves/templates/jenkins-slave-generic-template.yml"
    params: "{{ playbook_dir }}/params/jenkins-slaves/mvn"
    namespace: "{{ ci_cd.NAMESPACE }}"
    tags:
    - jenkins-slaves
    - mvn-slave
  - name: jenkins-slave-npm
    template: "https://raw.githubusercontent.com/redhat-cop/containers-quickstarts/v1.3/jenkins-slaves/templates/jenkins-slave-generic-template.yml"
    params: "{{ playbook_dir }}/params/jenkins-slaves/npm"
    namespace: "{{ ci_cd.NAMESPACE }}"
    tags:
    - jenkins-slaves
    - npm-slave
  - name: jenkins-slave-zap
    template: "https://raw.githubusercontent.com/redhat-cop/containers-quickstarts/v1.3/jenkins-slaves/templates/jenkins-slave-generic-template.yml"
    params: "{{ playbook_dir }}/params/jenkins-slaves/zap"
    namespace: "{{ ci_cd.NAMESPACE }}"
    tags:
    - jenkins-slaves
    - zap-slave
  - name: jenkins-slave-ansible
    template: "https://raw.githubusercontent.com/redhat-cop/containers-quickstarts/v1.3/jenkins-slaves/templates/jenkins-slave-generic-template.yml"
    params: "{{ playbook_dir }}/params/jenkins-slaves/ansible"
    namespace: "{{ ci_cd.NAMESPACE }}"
    tags:
      - jenkins-slaves
      - ansible-slave
  - name: jenkins-slave-arachni
    template: "https://raw.githubusercontent.com/redhat-cop/containers-quickstarts/v1.3/jenkins-slaves/templates/jenkins-slave-generic-template.yml"
    params: "{{ playbook_dir }}/params/jenkins-slaves/arachni"
    namespace: "{{ ci_cd.NAMESPACE }}"
    tags:
      - jenkins-slaves
      - arachni-slave
  - name: jenkins-slave-gradle
    template: "https://raw.githubusercontent.com/redhat-cop/containers-quickstarts/v1.3/jenkins-slaves/templates/jenkins-slave-generic-template.yml"
    params: "{{ playbook_dir }}/params/jenkins-slaves/gradle"
    namespace: "{{ ci_cd.NAMESPACE }}"
    tags:
      - jenkins-slaves
      - gradle-slave
  - name: jenkins-slave-golang
    template: "https://raw.githubusercontent.com/redhat-cop/containers-quickstarts/v1.3/jenkins-slaves/templates/jenkins-slave-generic-template.yml"
    params: "{{ playbook_dir }}/params/jenkins-slaves/golang"
    namespace: "{{ ci_cd.NAMESPACE }}"
    tags:
      - jenkins-slaves
      - golang-slave
  - name: jenkins-slave-mongodb
    template: "https://raw.githubusercontent.com/redhat-cop/containers-quickstarts/v1.3/jenkins-slaves/templates/jenkins-slave-generic-template.yml"
    params: "{{ playbook_dir }}/params/jenkins-slaves/mongodb"
    namespace: "{{ ci_cd.NAMESPACE }}"
    tags:
      - jenkins-slaves
      - mongodb-slave
  - name: jenkins-slave-python
    template: "https://raw.githubusercontent.com/redhat-cop/containers-quickstarts/v1.3/jenkins-slaves/templates/jenkins-slave-generic-template.yml"
    params: "{{ playbook_dir }}/params/jenkins-slaves/python"
    namespace: "{{ ci_cd.NAMESPACE }}"
    tags:
      - jenkins-slaves
      - python-slave
- object: ci-cd-deployments
  content:
  - name: sonarqube
    template: "https://raw.githubusercontent.com/rht-labs/openshift-templates/v1.0/sonarqube/template.yml"
    params: "{{ playbook_dir }}/params/sonarqube/deploy"
    namespace: "{{ ci_cd.NAMESPACE }}"
    tags:
    - sonarqube
    - sonarqube-deploy
  - name: sonarqube-postgresql
    template: "openshift//postgresql-persistent"
    params: "{{ playbook_dir }}/params/sonarqube/postgresql"
    namespace: "{{ ci_cd.NAMESPACE }}"
    tags:
    - sonarqube
    - sonarqube-postgresql
    - sonarqube-postgresql-deploy
  - name: nexus
    template: "https://raw.githubusercontent.com/rht-labs/openshift-templates/v1.0/nexus/template.yml"
    params: "{{ playbook_dir }}/params/nexus/deploy"
    namespace: "{{ ci_cd.NAMESPACE }}"
    tags:
    - nexus
    - nexus-deploy
  - name: jenkins-ephemeral
    template: "https://raw.githubusercontent.com/rht-labs/openshift-templates/v1.0/jenkins/jenkins-ephemeral-template.yml"
    params_from_vars: "{{ jenkins }}"
    params: "{{ playbook_dir }}/params/jenkins/deploy"
    namespace: "{{ ci_cd.NAMESPACE }}"
    tags:
    - jenkins
    - jenkins-deploy
