---
ansible_connection: local

deploy_key:
  SSH_PRIVATE_KEY: "{{ ci_cd_private_key }}"
  SECRET_NAME: "{{ ci_cd.SECRET_NAME }}"
nexus:
  USERNAME: "{{ nexus_username }}"
  PASSWORD: "{{ nexus_password }}"
  SECRET_NAME: "nexus-user-pass"
scm:
  USERNAME: "{{ bitbucket_username }}"
  PASSWORD: "{{ bitbucket_password }}"
  SECRET_NAME: "bitbucket-user-pass"

openshift_cluster_content:
- object: secrets
  content:
  - name: ci-cd-deploy-key
    template: "https://raw.githubusercontent.com/rht-labs/openshift-templates/v1.0/secrets/secret-ssh-private-key-template.yml"
    params_from_vars: "{{ deploy_key }}"
    namespace: "{{ ci_cd_namespace }}"
    tags:
    - ci-cd
    - deploy-key
  - name: nexus-admin-username-password
    template: "https://raw.githubusercontent.com/rht-labs/openshift-templates/v1.0/secrets/secret-user-pass-template.yml"
    params_from_vars: "{{ nexus }}"
    namespace: "{{ ci_cd_namespace }}"
    tags:
    - ci-cd
    - nexus-user-pass
  - name: scm-app-username-password
    template: "https://raw.githubusercontent.com/rht-labs/openshift-templates/v1.0/secrets/secret-user-pass-template.yml"
    params_from_vars: "{{ scm }}"
    namespace: "{{ ci_cd_namespace }}"
    tags:
    - ci-cd
    - scm-user-pass
